
# nome que vai aparecer la nas opções de pipe 
name: 'Execucao Agendada'

# triggers OU gatilhos de execução 
    # gatilho de exec manual = workflow_dispatch
on:
    schedule:
      - cron: '0 8 * * 1' 

jobs:

    # descricao do job
    e2e-tests:

        # maquina que o job via executar
        runs-on: ['ubuntu-latest']

        # passo a passo das acoes do job
        steps:
        
            - uses: actions/checkout@v4

            
           
            - name: 'Instalando Yarn'
              run: npm install -g yarn     

            - name: 'Instalando as dependencias'
              run: yarn  

            - name: 'Instalando Playwright'
              run: yarn  playwright install

            - name: 'Testes E2E (end-to-end)'
              run: yarn  run e2e

            # passed, failed, cancelled
            - uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: relatorio-de-testes
                path: ./playwright-report

            

        

    


