# CI de Nivel 03 - Disparo automático smepre outro for concluido , como deploy

# nome que vai aparecer la nas opções de pipe
name: 'Execucao por Deploy'

# regras de disparo da execucao (triggers/gatilhos)
# gatilho de exec após outro workflow - workflow_run

on:
  workflow_run:
    workflows: ['Execucao Manual']
    types:
      - completed

jobs:
  # descricao do job
  e2e-tests:
    # maquina que o job via executar
    runs-on: ubuntu-latest

    # passo a passo das acoes do job
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/checkout@v4
      #   with:
      #     node-version: lts/*

      - name: 'Instalando Yarn'
        run: npm install -g yarn

      - name: 'Instalando as dependencias'
        run: yarn

      - name: 'Instalando Playwright'
        run: yarn  playwright install

      - name: 'Testes E2E (end-to-end)'
        run: yarn  run e2e

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
