# nome que vai aparecer la nas opções de pipe
name: 'Execucao Integrada'

# triggers OU gatilhos de execução
# gatilho de exec manual = workflow_dispatch
on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Instalando Yarn'
        run: npm install -g yarn

      - name: 'Instalando as dependencias'
        run: yarn

      - name: Padronização de codigo (Lint)
        run: yarn lint

  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Instalando Yarn'
        run: npm install -g yarn

      - name: 'Instalando as dependencias'
        run: yarn

      - name: Testes de Unidade
        run: yarn run test

  # descricao do job
  e2e-tests:
    # maquina que o job via executar
    runs-on: ['ubuntu-latest']

    # passo a passo das acoes do job
    steps:
      - uses: actions/checkout@v4

      - name: 'Instalando Yarn'
        run: npm install -g yarn

      - name: 'Instalando as dependencias'
        run: yarn

      - name: 'Instalando Playwright'
        run: yarn  playwright install

      - name: 'Subir aplicacao local'
        run: yarn start &

      - name: 'Testes E2E (end-to-end)'
        run: yarn  run e2e
        env:
          URL: 'http://localhost:3000'

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
